In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

df = pd.read_csv('dataSet/DataSet.csv')

df = pd.get_dummies(df)


de = ['ระยะเวลาในเดือน']
X = df.drop(columns=de)
y = df['ระยะเวลาในเดือน']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=38)

model = DecisionTreeRegressor(random_state=38)

model.fit(X_train, y_train)

data_test = {
    '2.นักศึกษาสังกัดหลักสูตร': ['ปร.ด.สาขาวิชาเทคโนโลยียาง'],
    '3. เพศ': ['หญิง'],
    '4. อายุ (ปี)': [25],
    '6. สถานภาพสมรส (ปัจจุบัน)': ['โสด'],
    '7. ท่านมีความต้องการสำเร็จการศึกษาตามระยะเวลาที่หลักสูตรกำหนดหรือไม่': ['ต้องการ'],
    '8. ท่านทราบและเข้าใจถึงหลักเกณฑ์และวิธีการสำเร็จการศึกษาระดับบัณฑิตศึกษาหรือไม่': ['ทราบ'],
    'ความรู้ความเข้าใจแผนการเรียนที่กำหนดไว้ในหลักสูตร,ความรู้และความเข้าใจในการเรียนในแต่ละรายวิชา': ['ปานกลาง'],
    'หลักสูตรมีการจัดกิจกรรมการเรียนการสอนที่เน้นผู้เรียนเป็นสำคัญ': ['ปานกลาง'],
    'หลักสูตรมีความพร้อมของสถานที่ เครื่องมือ และอุปกรณ์การเรียน': ['ปานกลาง'],
    'การให้ความสนับสนุนข้อมูลต่างๆ ของเจ้าหน้าที่บัณฑิตศึกษา': ['ปานกลาง'],
    'การจัดเวลาให้นักศึกษาเข้าพบ': ['ปานกลาง'],
    'การวางแผนการเรียนระหว่างอาจารย์กับนักศึกษา': ['ปานกลาง'],
    'การติดตามการทำวิทยานิพนธ์ของนักศึกษาอย่างสม่ำเสมอ': ['ปานกลาง'],
    'การมีความรู้ความเข้าใจในกฎระเบียบ และข้อกำหนดเกี่ยวกับวิทยานิพนธ์': ['ปานกลาง'],
    'ความรอบรู้ และความชำนาญของอาจารย์ที่ปรึกษาในหัวข้อวิทยานิพนธ์': ['ปานกลาง'],
    'ความพร้อมในการเป็นอาจารย์ที่ปรึกษา': ['ปานกลาง'],
    'การสนับสนุนให้นักศึกษาขอทุนสนับสนุนการวิจัย': ['ปานกลาง'],
    'การสนับสนุนให้นักศึกษานำเสนอผลงานในที่ประชุมหรือตีพิมพ์ในวารสารวิชาการ': ['ปานกลาง'],
    'ความชื่นชอบอาจารย์ผู้สอน และอาจารย์ที่ปรึกษา': ['ปานกลาง'],
    'ปัจจัยส่งผลต่อการสำเร็จการศึกษาของนักศึกษาระดับบัณฑิตศึกษา (โปรดเลือกระดับความสำคัญที่ตรงกับความคิดเห็นของท่านมากที่สุดเพียงระดับเดียว) [3.1 การหาหัวข้อวิทยานิพนธ์]': ['ปานกลาง'],
    'การเขียนเค้าโครงวิทยานิพนธ์': ['ปานกลาง'],
    'การวางแผนและการดำเนินการวิทยานิพนธ์': ['ปานกลาง'],
    'สิ่งเร้าที่ทำให้นักศึกษามีพฤติกรรมในการอยากเรียนและศึกษาค้นคว้า(เพื่อนร่วมเรียนในชั้น,อุปกรณ์และเครื่องมือในการทดล': ['ปานกลาง'],
    'การเก็บรวบรวมข้อมูล': ['ปานกลาง'],
    'การวิเคราะห์ข้อมูล': ['ปานกลาง'],
    'การเขียนวิทยานิพนธ์': ['ปานกลาง'],
    'การสอบโครงร่างวิทยานิพนธ์': ['ปานกลาง'],
    'การสอบป้องกันร่างวิทยานิพนธ์': ['ปานกลาง'],
    'การส่งรูปเล่มวิทยานิพนธ์': ['ปานกลาง'],
    'การเผยแพร่ผลงานวิทยานิพนธ์': ['ปานกลาง'],
    'ท่านมีความรู้ความเข้าใจในกฎระเบียบและข้อกำหนดเกี่ยวกับวิทยานิพนธ์': ['ปานกลาง'],
    'มีวินัยในตนเอง': ['ปานกลาง'],
    'มีความใฝ่รู้ใฝ่เรียน': ['ปานกลาง'],
    'ท่านมีการเข้าพบอาจารย์ที่ปรึกษา หรือติดต่อประสานงานกับอาจารย์ที่ปรึกษา ผ่านช่องทางการสื่อสารต่างๆ': ['ปานกลาง'],
    'ท่านมีการวางแผนการเรียนระหว่างนักศึกษากับอาจารย์': ['ปานกลาง'],
    'ความรู้และความสามารถในการวิจัย เช่น การวางแผน/เก็บตัวอย่าง/ทำแลป': ['ปานกลาง'],
    'มีความสามารถในการสืบค้นข้อมูลในการทำวิทยานิพนธ์ และแหล่งเรียนรู้ต่างๆ,ท่านมีทักษะการเขียน การวิเคราะห์ สรุปผล': ['ปานกลาง'],
    'เมื่อท่านสำเร็จการศึกษาระดับปริญญาตรี ท่านมีความประสงค์จะศึกษาต่อระดับบัณฑิตศึกษา': ['ปานกลาง'],
    'มีความต้องการหาประสบการณ์และหาความรู้เพิ่มเติม': ['ปานกลาง'],
    'มีความเป็นไปได้มากน้อยเพียงใดที่คุณจะแนะนำเราให้กับเพื่อนหรือผู้ร่วมงาน': ['ปานกลาง'],
    'แรงผลักดันจากครอบครัว': ['ปานกลาง'],
    'สภาพคล่องด้านการเงิน': ['น้อย'],
    'ต้องปฏิบัติงานประจำควบคู่ไปด้วยหรือไม่': ['ปฏิบัติ']
}

df_test = pd.DataFrame(data_test)

df_test = pd.get_dummies(df_test)

df_test = df_test.reindex(columns=X.columns, fill_value=0)

y_pred_custom = model.predict(df_test)

years_predicted = y_pred_custom / 12

print("-ผลการทำนาย-");
print(f'จบการศึกษาภายในประมาณช่วง: {years_predicted[0]:.0f} ปี')

average_duration_months = y.mean()
prediction_percentage = (y_pred_custom[0] / average_duration_months) * 100

print(f'เปอร์เซ็นต์การทำนาย: {prediction_percentage:.2f}%')

y_pred = model.predict(X_test)

#mse = mean_squared_error(y_test, y_pred)
#print(f'Mean Squared Error on Test Set: {mse}')



cfmx = confusion_matrix(y_test, y_pred)
print()
# Display confusion matrix and evaluation metrics
print('Confusion Matrix:')
print(cfmx)
print()

score = model.score(X_train, y_train)
print(f'R²: {score*100:.2f}%')
err = (cfmx[0, 1] + cfmx[1, 0]) / y_test.count()
print(f'Error Rate: {err:.2f}')

print()
print('Classification Report:')
print(classification_report(y_test, y_pred))

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

model.fit(X, y)
plt.figure(figsize=(25, 20))
t = plot_tree(model,
    feature_names=X.columns,
    class_names=y,
    label='all',
    impurity=True,
    precision=3,
    filled=True,
    rounded=True,
    fontsize=16)
plt.show()

-ผลการทำนาย-
จบการศึกษาภายในประมาณช่วง: 3 ปี
เปอร์เซ็นต์การทำนาย: 98.18%

Confusion Matrix:
[[0 0 0 0 2 0 0]
 [1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]]

R²: 100.00%
Error Rate: 0.14

Classification Report:
              precision    recall  f1-score   support

        24.0       0.00      0.00      0.00         2
        26.0       0.00      0.00      0.00         1
        30.0       1.00      1.00      1.00         1
        33.0       0.00      0.00      0.00         0
        36.0       0.25      1.00      0.40         1
        42.0       0.00      0.00      0.00         1
        48.0       0.00      0.00      0.00         1

    accuracy                           0.29         7
   macro avg       0.18      0.29      0.20         7
weighted avg       0.18      0.29      0.20         7



c:\xampp\htdocs\Python\Datamining\Project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\xampp\htdocs\Python\Datamining\Project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\xampp\htdocs\Python\Datamining\Project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

ModuleNotFoundError: No module named 'matplotlib'

In [6]:
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error
)

# =====================================================
# LOAD DATA
# =====================================================

df = pd.read_csv('dataSet/DataSet.csv')

# แปลง categorical -> numerical
df = pd.get_dummies(df)

# =====================================================
# DEFINE X AND y
# =====================================================

target = 'ระยะเวลาในเดือน'

X = df.drop(columns=[target])
y = df[target]

# =====================================================
# CREATE MODEL
# =====================================================

model = DecisionTreeRegressor(
    random_state=38,
    max_depth=5
)

# =====================================================
# K-FOLD CROSS VALIDATION
# =====================================================

kfold = KFold(
    n_splits=5,
    shuffle=True,
    random_state=38
)

# ---------- R² ----------
r2_scores = cross_val_score(
    model,
    X,
    y,
    cv=kfold,
    scoring='r2'
)

# ---------- MSE ----------
mse_scores = cross_val_score(
    model,
    X,
    y,
    cv=kfold,
    scoring='neg_mean_squared_error'
)

mse_scores = -mse_scores

# ---------- RMSE ----------
rmse_scores = np.sqrt(mse_scores)

# ---------- MAE ----------
mae_scores = cross_val_score(
    model,
    X,
    y,
    cv=kfold,
    scoring='neg_mean_absolute_error'
)

mae_scores = -mae_scores

# =====================================================
# SHOW RESULTS
# =====================================================

print("\n========== K-FOLD RESULT ==========\n")

print("R² ของแต่ละ Fold:")
print(r2_scores)

print(f"\nAverage R²: {r2_scores.mean()*100:.2f}%")

print("\nMSE ของแต่ละ Fold:")
print(mse_scores)

print(f"\nAverage MSE: {mse_scores.mean():.2f}")

print("\nRMSE ของแต่ละ Fold:")
print(rmse_scores)

print(f"\nAverage RMSE: {rmse_scores.mean():.2f}")

print("\nMAE ของแต่ละ Fold:")
print(mae_scores)

print(f"\nAverage MAE: {mae_scores.mean():.2f}")

# =====================================================
# TRAIN WITH ALL DATA
# =====================================================

model.fit(X, y)

# =====================================================
# CUSTOM INPUT
# =====================================================

data_test = {
    '2.นักศึกษาสังกัดหลักสูตร': ['ปร.ด.สาขาวิชาเทคโนโลยียาง'],
    '3. เพศ': ['หญิง'],
    '4. อายุ (ปี)': [25],
    '6. สถานภาพสมรส (ปัจจุบัน)': ['โสด'],
    '7. ท่านมีความต้องการสำเร็จการศึกษาตามระยะเวลาที่หลักสูตรกำหนดหรือไม่': ['ต้องการ'],
    '8. ท่านทราบและเข้าใจถึงหลักเกณฑ์และวิธีการสำเร็จการศึกษาระดับบัณฑิตศึกษาหรือไม่': ['ทราบ']
}

# =====================================================
# PREPARE TEST DATA
# =====================================================

df_test = pd.DataFrame(data_test)

df_test = pd.get_dummies(df_test)

df_test = df_test.reindex(columns=X.columns, fill_value=0)

# =====================================================
# PREDICT
# =====================================================

y_pred = model.predict(df_test)

predicted_months = y_pred[0]
predicted_years = predicted_months / 12

print("\n========== PREDICTION ==========\n")

print(f"คาดว่าจะจบภายในประมาณ {predicted_years:.1f} ปี")

avg_month = y.mean()

percent = (predicted_months / avg_month) * 100

print(f"เปอร์เซ็นต์เทียบค่าเฉลี่ย: {percent:.2f}%")


========== K-FOLD RESULT ==========

R² ของแต่ละ Fold:
[-0.14783159  0.1543341  -0.01954748  0.33318806  0.484375  ]

Average R²: 16.09%

MSE ของแต่ละ Fold:
[ 87.7037037   55.9175     359.17201166  85.          90.75      ]

Average MSE: 135.71

RMSE ของแต่ละ Fold:
[ 9.36502556  7.47780048 18.95183399  9.21954446  9.52627944]

Average RMSE: 10.91

MAE ของแต่ละ Fold:
[ 8.19047619  4.77857143 10.97959184  5.66666667  8.5       ]

Average MAE: 7.62

========== PREDICTION ==========

คาดว่าจะจบภายในประมาณ 2.9 ปี
เปอร์เซ็นต์เทียบค่าเฉลี่ย: 94.55%


In [ ]:
import pandas as pd
df = pd.read_csv('dataSet/Data2.csv', encoding='TIS-620')
df.to_csv('dataSet/Data3.csv', index=False)